#!/bin/bash
export MATK_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
export DOCKER_PATH="${MATK_PATH}/.docker"
export NPROC="$( nproc )"

if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"     # v1
else
    DOCKER_COMPOSE_CMD="docker compose"     # v2
fi

fn_help()
{
    echo "matk command script"
    echo
    echo "Usage: "
    echo "  matk up                 run the kyumatic env in background"
    echo "  matk down               teardown all kyumatic env"
    echo "  matk build              build docker-compose image"
    echo "  matk bash               get the interactive bash shell"
    echo "  matk <cmd> <args>       execute cmd with args on container"
    echo "  matk [help|-h|--help]   show this help"
    echo
    echo "  examples:"
    echo "    ./matk up"
    echo "    ./matk python main.py"
    echo
}

[[ $# -lt 1 ]] && fn_help && exit 1

cmd_prefix="${DOCKER_COMPOSE_CMD} -f ${DOCKER_PATH}/docker-compose.yml -p matk"
cmd_str="${@:1}"
set -x 

case $1 in
    "up")
        ${cmd_prefix} up -d --remove-orphans
        #${cmd_prefix} up
        ;;
    "down")
        ${cmd_prefix} down --remove-orphans
        ;;
    "build")
        ${cmd_prefix} build --progress plain matk
        ;;
    "bash")
        ${cmd_prefix} up -d --remove-orphans
        ${cmd_prefix} exec matk /bin/bash -l
        ;;
    "help")
        fn_help
        ;;
    "-h")
        fn_help
        ;;
    "--help")
        fn_help
        ;;
    *)
        ${cmd_prefix} up -d --remove-orphans
        ${cmd_prefix} exec matk ${cmd_str}
        ;;
esac
