#!/bin/bash
export MATK_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
export DOCKER_PATH="${MATK_PATH}/.docker"

if command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE_CMD="docker-compose"     # v1
else
    DOCKER_COMPOSE_CMD="docker compose"     # v2
fi

fn_help()
{
    echo "matk command script"
    echo
    echo "Usage: "
    echo "  matk up         run the kyumatic env in background"
    echo "  matk down       teardown all kyumatic env"
    echo "  matk <cmd>      interactive command execution on container"
    echo
    echo "  examples:"
    echo "    math up"
    echo "    math python main.py"
    echo
}

[[ $# -lt 1 ]] && fn_help && exit 1

cmd_prefix="${DOCKER_COMPOSE_CMD} -f ${DOCKER_PATH}/docker-compose.yml -p matk"

case $1 in
    "up")
        ${cmd_prefix} up -d --remove-orphans
        ;;
    "down")
        ${cmd_prefix} down --remove-orphans
        ;;
    "help")
        fn_help
        ;;
    "-h")
        fn_help
        ;;
    *)
        ${cmd_prefix} up -d --remove-orphans
        ${cmd_prefix} exec matk ${@:1}
        ;;
esac
