version: '3'

services:
  db:
    image: postgres
    volumes:
      - localdb:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - TZ=US/Eastern
      - PGTZ=UTC
      - POSTGRES_DB=c2tk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  c2tk:
    build:
      context: ${C2TK_PATH}
      dockerfile: ${C2TK_PATH}/.docker/Dockerfile
      args:
        - NPROC=${NPROC}
    volumes:
      - ${C2TK_PATH}:/c2tk
      - ${C2TK_PATH}/.settings/ipython_config.py:/root/.ipython/profile_default/ipython_config.py:ro
      - ${C2TK_PATH}/.settings/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py:ro
    shm_size: '1gb'
    ports:
      - 8989:8989
    working_dir: /c2tk
    stdin_open: true
    tty: true
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    sysctls:
        - net.ipv4.tcp_keepalive_time=200
        - net.ipv4.tcp_keepalive_intvl=200
        - net.ipv4.tcp_keepalive_probes=5
    command: >
      bash -c "pip install -e .
      && pip install -U -r requirements.txt
      && jupyter notebook"

volumes:
  localdb:
    driver: local
