version: '3'

services:
  db:
    image: postgres
    volumes:
      - localdb:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - TZ=US/Eastern
      - PGTZ=UTC
      - POSTGRES_DB=c2tk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  c2tk:
    build:
      context: ${C2TK_PATH}
      dockerfile: .docker/Dockerfile
      args:
        - NPROC=${NPROC}
        - USERNAME=${DOCKER_USER}
        - USERID=${USERID}
        - GROUPID=${GROUPID}
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          device_ids: ['0', '1']
    #          capabilities: [gpu]
    #ipc: host
    shm_size: 2048M
    volumes:
      - ${C2TK_PATH}:/home/${DOCKER_USER}/c2tk
    environment:
      - NPROC=${NPROC}
      - OMP_NUM_THREADS=${NPROC}
      - C2TK_PATH=/home/${DOCKER_USER}/c2tk
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_PORT=${JUPYTER_PORT}
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    working_dir: /home/${DOCKER_USER}/c2tk
    stdin_open: true
    tty: true
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    sysctls:
        - net.ipv4.tcp_keepalive_time=200
        - net.ipv4.tcp_keepalive_intvl=200
        - net.ipv4.tcp_keepalive_probes=5
    user: ${USERID}:${GROUPID}
    command: >
      bash -c "pip install -U --no-deps -e .
      && jupyter lab"

volumes:
  localdb:
    driver: local
